### ISSUE TITLE
Robust gap filling approach for time-series data 

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [mlr-org/mlr3spatial#1]
Hi,

Can we have a gap filling approach within `mlr3raster`?
- Technically speaking there are some existing approaches for gap filling data and specially for a huge stack of satellite imagery data as in the libraries such as [Gdalcube](https://cran.r-project.org/web/packages/gdalcubes/index.html), which includes:
    - linear approaches like `mean`  
    - `repeat last seen observation`
    - etc.
but a robust method for such a challenge is missing. That  is why I asked about develop/adopting an approach to address the challenge.

Here are some examples of the problem and solutions for your reference:
[LINK1](https://gking.harvard.edu/amelia)
[LINK2](https://bg.copernicus.org/articles/10/4055/2013/bg-10-4055-2013.pdf)
[LINK3](https://www.sciencedirect.com/science/article/pii/S0924271614002512)

Best, Mo

**Comment by pat-s** [comment]
Would potentially fit though I see also the potential to implement a PipeOp for this in {mlr3pipelines} (or here) as all preprocessing operations are bundles as PipeOps essentially.

Though I do not have time any time soon to tackle this. PRs welcome!

**Comment by pat-s** [comment]
This is a complicated request and while we might want to tackle this at some point, we first need to get the basic functionality (data storage, prediction) going here.

If someone wants to work on this, please reach out to us here or in Mattermost.
