### ISSUE TITLE
Discussions around predict functionality

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatial#11]
How do we want to handle predictions?

1. S3 generic
2. R6 method 
3. standalone function

I'd favor (1) as this would play well with `predict()` calls for different classes (terra, raster, stars).

cc @be-marc

**Comment by be-marc** [comment]
We decided against an S3 generic in `mlr3` to keep the return of `predict_newdata` consistent. We should use the standalone function in #13.

**Comment by pat-s** [comment]
Ok. Should the name stay like `predict_raster()`? I am wondering if this is too close to the old {raster} package and if something like `predict_spatial()` might be more generic?

This also relates to the question if we want to have S3 generic like `predict_raster()` covering all spatial packages or if we want to have one function per package (terra, raster, stars).
Given that arguments will most likely be the same, we could use a S3 generic?

**Comment by be-marc** [comment]
I like `predict_spatial()` which should be an S3 generic.

**Comment by be-marc** [comment]
But we cannot dispatch in on the `DataBackend` of the `Task`, right?

**Comment by pat-s** [comment]
For `predict_newdata_spatial()` users would directly pass the spatial object, so this could work, couldn't it?

For `predict_spatial()`: Is the DataBackend type stored in a task? Idk out of the box right now. If so, we could make use of it.

**Comment by be-marc** [comment]
> For predict_newata_spatial() users would directly pass the spatial object, so this could work, couldn't it?

Yes. The function calls `as_data_backend` on the raster stack and uses `learner$state$train_task` to construct a valid task. Then just call `predict_spatial()`.

> For predict_spatial(): Is the DataBackend type stored in a task? Idk out of the box right now. If so, we could make use of it.

Yes `class(task$backend)`.

**Comment by pat-s** [comment]
Finished discussion, we decided on `predict_spatial()`.
