### ISSUE TITLE
Change request because of changed behavior of `terra::sources` 

### ISSUE THREAD

**Issue by rhijmans** [mlr-org/mlr3spatial#29]
In `DataBackendRaster`  there is this line 

      private$.data = terra::sources(assert_class(data, "SpatRaster"))$source

This breaks with the development version of `terra` because `terra::sources(data)` now returns a vector. It should work with both CRAN and the devel version if you change it to

      private$.data = terra::sources(assert_class(data, "SpatRaster"), TRUE)$source

Can you please make that change?

**Comment by be-marc** [comment]
Thanks for reporting.  Fixed by #31 . We upload to CRAN soon.
