### ISSUE TITLE
Error by DataBackendRaster with SpatRaster (terra package)

### ISSUE THREAD

**Issue by Hallo951** [mlr-org/mlr3spatial#35]
Hello

I am trying to speed up the prediction of a random forest model and a SpatRaster using this package. However, I keep getting the same error message when creating the "backend" using the "DataBackendRaster" function. The error is:

> Error: $ operator is invalid for atomic vectors

Here is a minimal example:

```
library("mlr3")
library("mlr3spatial")

# SpatRaster demo stack
stack_terra = demo_stack_spatraster(5)

# tasks
backend_terra = DataBackendRaster$new(stack_terra)
task_terra = as_task_regr(backend_terra, target = "x_1")

# Train learners
set.seed(42)
row_ids = sample(1:task_terra$nrow, 50)
learner_task_terra = lrn("regr.rpart")
learner_task_terra$parallel_predict = TRUE
learner_task_terra$train(task_terra, row_ids = row_ids)

# prediction
plan(multicore, workers = 4)
frank_parallel <- predict_spatial(task_terra, learner_task_terra, chunksize = 2000L)
```

Why doesn't this work?

Here my session:

> R version 4.0.5 (2021-03-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] mapmisc_1.8.0       terra_1.5-12        RColorBrewer_1.1-2  ecospat_3.2.1       gbm_2.1.8           ape_5.6-1           ade4_1.7-18         plyr_1.8.6         
>  [9] openxlsx_4.2.5      data.table_1.14.2   foreach_1.5.1       rlist_0.4.6.2       stringr_1.4.0       latticeExtra_0.6-29 viridis_0.6.2       viridisLite_0.4.0  
> [17] rasterVis_0.51.1    lattice_0.20-41     rmaxent_0.8.5.9000  devtools_2.4.3      usethis_2.1.5       rJava_1.0-6         jsonlite_1.7.3      ENMeval_2.0.3      
> [25] magrittr_2.0.1      sf_1.0-5            rgeos_0.5-9         dismo_1.3-5         raster_3.5-11       sp_1.4-6            mlr3tuning_0.9.0    paradox_0.7.1      
> [33] mlr3spatial_0.1.0   mlr3_0.13.1        
> 
> loaded via a namespace (and not attached):
>   [1] SparseM_1.81          ModelMetrics_1.2.2.2  earth_5.3.1           nabor_0.5.0           tidyr_1.1.4           ggplot2_3.3.5         knitr_1.37           
>   [8] multcomp_1.4-18       rpart_4.1-15          doParallel_1.0.16     generics_0.1.1        callr_3.7.0           TH.data_1.1-0         polspline_1.1.19     
>  [15] proxy_0.4-26          future_1.23.0         ecodist_2.0.7         adehabitatMA_0.3.14   spatstat.data_2.1-2   xml2_1.3.3            lubridate_1.8.0      
>  [22] adehabitatLT_0.3.25   assertthat_0.2.1      gower_0.2.2           xfun_0.29             adehabitatHR_0.4.19   fansi_1.0.2           DBI_1.1.2            
>  [29] htmlwidgets_1.5.4     reshape_0.8.8         spatstat.geom_2.3-1   stats4_4.0.5          purrr_0.3.4           ellipsis_0.3.2        ks_1.13.3            
>  [36] dplyr_1.0.7           ggpubr_0.4.0          backports_1.4.1       permute_0.9-5         deldir_1.0-6          vctrs_0.3.8           remotes_2.4.2        
>  [43] quantreg_5.86         abind_1.4-5           caret_6.0-90          cachem_1.0.6          withr_2.4.3           checkmate_2.0.0       rgdal_1.5-28         
>  [50] vegan_2.5-7           prettyunits_1.1.1     mclust_5.4.9          goftest_1.2-3         cluster_2.1.1         crayon_1.4.2          recipes_0.1.17       
>  [57] pkgconfig_2.0.3       units_0.7-2           nlme_3.1-152          pkgload_1.2.4         nnet_7.3-15           rlang_0.4.12          globals_0.14.0       
>  [64] lifecycle_1.0.1       MatrixModels_0.5-0    sandwich_3.0-1        palmerpenguins_0.1.0  PresenceAbsence_1.1.9 biomod2_3.5.1         randomForest_4.6-14  
>  [71] rprojroot_2.0.2       polyclip_1.10-0       matrixStats_0.61.0    Matrix_1.3-2          carData_3.0-5         boot_1.3-28           zoo_1.8-9            
>  [78] base64enc_0.1-3       processx_3.5.2        png_0.1-7             KernSmooth_2.23-18    pROC_1.18.0           classInt_0.4-3        maxnet_0.1.4         
>  [85] maptools_1.1-2        parallelly_1.30.0     jpeg_0.1-9            rstatix_0.7.0         ggsignif_0.6.3        scales_1.1.1          memoise_2.0.1        
>  [92] hexbin_1.28.2         compiler_4.0.5        plotrix_3.8-2         cli_3.1.0             listenv_0.8.0         ps_1.6.0              htmlTable_2.4.0      
>  [99] Formula_1.2-4         MASS_7.3-53.1         mgcv_1.8-34           tidyselect_1.1.1      stringi_1.7.6         forcats_0.5.1         SDMtune_1.1.5        
> [106] spatstat.linnet_2.3-1 tools_4.0.5           mlr3misc_0.10.0       future.apply_1.8.1    CircStats_0.2-6       rstudioapi_0.13       uuid_1.0-3           
> [113] foreign_0.8-81        snowfall_1.84-6.1     gridExtra_2.3         prodlim_2019.11.13    ENMTools_1.0.5        digest_0.6.29         pracma_2.3.6         
> [120] lava_1.6.10           TeachingDemos_2.12    Rcpp_1.0.8            car_3.0-12            usdm_1.1-18           broom_0.7.11          httr_1.4.2           
> [127] mda_0.5-2             colorspace_2.0-2      rvest_1.0.2           fs_1.5.2              tensor_1.5            splines_4.0.5         lgr_0.4.3            
> [134] bbotk_0.4.0           conquer_1.2.1         spatstat.utils_2.3-0  sessioninfo_1.2.2     spatstat_2.3-0        timeDate_3043.102     poibin_1.5           
> [141] plotmo_3.6.1          testthat_3.1.1        ipred_0.9-12          R6_2.5.1              Hmisc_4.6-0           lhs_1.1.3             pillar_1.6.4         
> [148] htmltools_0.5.2       glue_1.6.0            fastmap_1.1.0         class_7.3-20          codetools_0.2-18      pkgbuild_1.3.1        mvtnorm_1.1-3        
> [155] utf8_1.2.2            spatstat.sparse_2.1-0 tibble_3.1.6          gtools_3.9.2          zip_2.2.0             survival_3.2-10       desc_1.4.0           
> [162] munsell_0.5.0         e1071_1.7-9           iterators_1.0.13      reshape2_1.4.4        gtable_0.3.0          spatstat.core_2.3-2   rms_6.2-0

**Comment by be-marc** [comment]
Thanks for reporting. Just install the latest version form github. This was fixed a few hours ago.

**Comment by Hallo951** [comment]
Thanks, with the github version is all ok. A other little question: How use the rf model inside the spatial.predict function? Can you help me?

**Comment by be-marc** [comment]
You mean using random forest instead of rpart?
