### ISSUE TITLE
Stars object from tutorial - No method or default for coercing "RasterBrick" to "SpatRaster"

### ISSUE THREAD

**Issue by damondamondamon** [mlr-org/mlr3spatial#38]
Hey everybody,

I am using R 4.1.0 on Ubuntu 20.04 LTS.

I was trying out your workflow from the tutorial:
https://mlr3spatial.mlr-org.com/articles/mlr3spatial.html
I already get stuck when defining the backend, using
`backend = as_data_backend(stack)`
gives me:
`Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterBrick” to “SpatRaster”`

I can read the tif from the stars package and the stack without problems. I get the same error with my own stars object read from a tif object.

Same happens with the stack_raster from the benchmark tutorial:
https://mlr3spatial.mlr-org.com/articles/benchmark.html
`backend_raster = DataBackendRaster$new(stack_raster)`
gives me:
`Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterBrick” to “SpatRaster”`

I had the latest version for mlr3 and mlr3spatial. I just updated stars from 0.5.3 to 0.5.5 and also got this message while installing (not an error though):
` in method for ‘coerce’ with signature ‘"stars","Raster"’: no definition for class “Raster” `
` in method for ‘coerce’ with signature ‘"stars_proxy","Raster"’: no definition for class “Raster” `
` in method for ‘coerce’ with signature ‘"stars","SpatRaster"’: no definition for class “SpatRaster” `
` in** method for ‘coerce’ with signature ‘"stars_proxy","SpatRaster"’: no definition for class “SpatRaster” `
` in method for ‘coerce’ with signature ‘"stars","Spatial"’: no definition for class “Spatial” `
` in method for ‘coerce’ with signature ‘"stars","STFDF"’: no definition for class “STFDF”  `

Re-installed both sf and stars, still same problem. Assigning the original stars object (`stack`) to the class "Raster" or "SpatRaster" actually works. There seems to be an intermediate step where "stack" is conversed to a RasterBrick or falsely assumed to be a RasterBrick?

Doing it manually worked for me:
`sr_stack = as(stack, "SpatRaster") `
`backend = DataBackendRaster$new(sr_stack) `
Any ideas?

Thanks in advance,
Damon

**Comment by be-marc** [comment]
Hey,
thanks for reporting. It seems that the CRAN Version of stars and mlr3spatial no longer work together. We already added the new conversion method to the GitHub version of mlr3spatial. You can install the dev version with `remotes::install_github("mlr-org/mlr3spatial")`. Use the [dev version](https://mlr3spatial.mlr-org.com/dev/articles/mlr3spatial.html) of the tutorial because the layer names changed. I will update mlr3spatial on CRAN.

**Comment by be-marc** [comment]
The new CRAN version is online.
