### ISSUE TITLE
Update logger hierarchy

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatial#59]
@be-marc Currently the logger for mlr3spatial lives on the same level as the one for mlr3.
The recommended way for frameworks like mlr3 is actually to have it defined as a child-logger to mlr3.

mlr3pipelines already does so (and I've just added support in mlr3spatiotempcv)

```r
> lgr::logger_tree()
root [info] -> 1 appender              
├─mlr3                                 
│ ├─mlr3pipelines
│ └─mlr3spatiotempcv [warn]            
└─mlr3spatial 
```

See https://s-fleck.github.io/lgr/articles/lgr.html#hierarchy and https://github.com/mlr-org/mlr3pipelines/blob/5e2c8ee2f2516e9b70829cf8bfeb49a0023c7fa2/R/zzz.R#L26

**Comment by be-marc** [comment]
We cannot use child-logger in bbotk and mlr3tuning. It might be easier for the user to keep all loggers on the same level. This means we should change mlr3pipelines.

**Comment by pat-s** [comment]
I see! Good that you evaluated that already.

Should we have pkg specific loggers at all? Or just work with a central `mlr3` logger?

**Comment by be-marc** [comment]
> Should we have pkg specific loggers at all?

The bbotk logger is very useful to hide the resampling iteration logs during tuning. I think mlr3spatial is not needed. What about mlr3spatiotempcv?

**Comment by be-marc** [comment]
Switch to mlr3 logger 3e49df00d5bde485b795b308702cc0a1f68aca12
