### ISSUE TITLE
`predict_spatial()`: Create unsupervised task internally?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatial#67]
And let users just pass the raster file directly?

**Comment by pat-s** [comment]
@be-marc This got a few questions during the last workshop. I wonder if we should handle this internally? 
I can't remember if something was preventing is from doing so?

**Comment by be-marc** [comment]
No, not technically. I'm not sure to what degree we should hide things from the user.

**Comment by pat-s** [comment]
Think of the average (spatial) modeling user: the user is doing a prediction and then sees the use of `as_unsupervised_task()` and thinks: "wait, what does this do now and why is it needed?". The point is that usually people rarely use unsupervised tasks and there is no other occurrence AFAICS where this is needed to execute a prediction scenario.

It then happened that I had to explain this (or I rather said: "well, there are technical reasons why we need to do so but you don't need to worry" because there is no time in a presentation to go deeper into this and it might confuse people even (more) at this point).

I think it might be better if
- we allow passing the raster directly
- document the use of of the unsupervised task in the help page of `predict_spatial()`

In the end users want to predict **on a raster** and they don't really care if this one needs to be wrapped into an unsupervised task, mainly because for internal mlr3 reasons.

What do you think?

**Comment by be-marc** [comment]
I think this only works if the user is not making a mistake. For example, if the user passes a raster to `predict_spatial()` with a missing spectral band. He will get an error from the learner that `TaskUnsupervised` misses a feature. The user did not create a `TaskUnsupervised` so this might be confusing.

We often pass a task to a learner for making predictions. It's one of the first things the user learns in the book. I think the API is fine like this.

**Comment by be-marc** [comment]
I changed my mind. Passing spatial objects is now supported. `TaskUnsupervised` still works but will be removed from the docs.
